### ISSUE TITLE
Typed promise

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [xiscodev/promise-with-state#4]
With promises we can do `Promise<number>`. It would be nice if we could do `QueryablePromise<number>`, instead of having `any` as the promise result type.

**Comment by xoxefdp** [comment]
Promises will typed in next version 1.2.0 also

**Comment by xoxefdp** [comment]
> With promises we can do `Promise<number>`. It would be nice if we could do `QueryablePromise<number>`, instead of having `any` as the promise result type.


Promises will typed in next version 1.2.0 also

**Comment by ChocolateLoverRaj** [comment]
Btw I don't use TypeScript anymore. I switched to Rust. So I'm ok with these issues not being implemented.

**Comment by xoxefdp** [comment]
Solved after merge!

![Captura desde 2024-05-13 10-45-11](https://github.com/xiscodev/promise-with-state/assets/4589403/19b0a6ac-7d35-4934-b9e0-1d6325389768)
