### ISSUE TITLE
`dist/main.d.ts` Not published

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [xiscodev/promise-with-state#5]
Here you can see that the file is missing: https://www.jsdelivr.com/package/npm/promise-with-state?path=dist&version=1.1.1. Because of this TypeScript isn't able to load the types for this package.

**Comment by xoxefdp** [comment]
will be uploading with version 1.2.0 soon

**Comment by xoxefdp** [comment]
> Here you can see that the file is missing: https://www.jsdelivr.com/package/npm/promise-with-state?path=dist&version=1.1.1. Because of this TypeScript isn't able to load the types for this package.


will be uploading ir with package 1.2.0 soon

**Comment by xoxefdp** [comment]
Solved after merge!

![Captura desde 2024-05-13 10-45-11](https://github.com/xiscodev/promise-with-state/assets/4589403/22fb48fc-cafb-4ffa-a3a2-240a0872edf1)
